index:
    pattern:  /
    defaults: { _controller: WebMainBundle:Default:index }

map:
    pattern: /map
    defaults: { _controller: WebMainBundle:Default:map }

favoris:
    pattern: /favoris
    defaults: { _controller: WebMainBundle:Default:favoris }

add_favori:
    pattern: /add-favoris
    defaults: { _controller: WebMainBundle:Default:addFavori }

delete_favori:
    pattern: /delete-favoris/{id}
    defaults: { _controller: WebMainBundle:Default:deleteFavori }