index:
    pattern:  /
    defaults: { _controller: WebMainBundle:Default:index }

map:
    pattern: /map
    defaults: { _controller: WebMainBundle:Default:map }
favoris:
    pattern: /favoris
    defaults: { _controller: WebMainBundle:Default:favoris }